package net.ilexiconn.paleocraft.client.model;

import net.ilexiconn.llibrary.client.model.tools.AdvancedModelBase;
import net.ilexiconn.llibrary.client.model.tools.AdvancedModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class DromaeosaurusModel extends AdvancedModelBase {
    public AdvancedModelRenderer leftArm1;
    public AdvancedModelRenderer rightArm1;
    public AdvancedModelRenderer neck1;
    public AdvancedModelRenderer neck2;
    public AdvancedModelRenderer body;
    public AdvancedModelRenderer leftLeg1;
    public AdvancedModelRenderer head;
    public AdvancedModelRenderer tail1;
    public AdvancedModelRenderer rightLeg1;
    public AdvancedModelRenderer leftArm2;
    public AdvancedModelRenderer leftArmClaws;
    public AdvancedModelRenderer rightArm2;
    public AdvancedModelRenderer rightArmClaws;
    public AdvancedModelRenderer leftLeg2;
    public AdvancedModelRenderer leftFoot;
    public AdvancedModelRenderer leftClaw;
    public AdvancedModelRenderer crest;
    public AdvancedModelRenderer snoutTip;
    public AdvancedModelRenderer snout;
    public AdvancedModelRenderer tail2;
    public AdvancedModelRenderer rightLeg2;
    public AdvancedModelRenderer rightFoot;
    public AdvancedModelRenderer rightClaw;
    public AdvancedModelRenderer tail3;
    public AdvancedModelRenderer tail4;
    public AdvancedModelRenderer tail5;
    public AdvancedModelRenderer tail4Fan;
    public AdvancedModelRenderer tail5Fan;

    public DromaeosaurusModel() {
        textureWidth = 100;
        textureHeight = 100;

        leftArm1 = new AdvancedModelRenderer(this, "LeftArm1");
        leftArm1.mirror = false;
        leftArm1.addBox(0.0F, -5.0F, -4.0F, 1, 5, 5);
        leftArm1.setTextureSize(100, 100);
        rightArm1 = new AdvancedModelRenderer(this, "RightArm1");
        rightArm1.mirror = false;
        rightArm1.addBox(-1.0F, -5.0F, -4.0F, 1, 5, 5);
        rightArm1.setTextureSize(100, 100);
        neck1 = new AdvancedModelRenderer(this, "Neck1");
        neck1.mirror = false;
        neck1.addBox(-2.0F, -1.0F, 0.0F, 4, 5, 3);
        neck1.setTextureSize(100, 100);
        neck2 = new AdvancedModelRenderer(this, "Neck2");
        neck2.mirror = false;
        neck2.addBox(-1.0F, -2.5F, 0.0F, 2, 4, 7);
        neck2.setTextureSize(100, 100);
        body = new AdvancedModelRenderer(this, "Body");
        body.mirror = false;
        body.addBox(-3.0F, -4.0F, -11.0F, 6, 7, 11);
        body.setTextureSize(100, 100);
        leftLeg1 = new AdvancedModelRenderer(this, "LeftLeg1");
        leftLeg1.mirror = false;
        leftLeg1.addBox(0.0F, -6.0F, -2.5F, 2, 8, 5);
        leftLeg1.setTextureSize(100, 100);
        head = new AdvancedModelRenderer(this, "Head");
        head.mirror = false;
        head.addBox(-1.5F, -2.0F, -1.0F, 3, 4, 5);
        head.setTextureSize(100, 100);
        tail1 = new AdvancedModelRenderer(this, "Tail1");
        tail1.mirror = false;
        tail1.addBox(-2.5F, -3.0F, -3.0F, 5, 6, 3);
        tail1.setTextureSize(100, 100);
        rightLeg1 = new AdvancedModelRenderer(this, "RightLeg1");
        rightLeg1.mirror = false;
        rightLeg1.addBox(-2.0F, -6.0F, -2.5F, 2, 8, 5);
        rightLeg1.setTextureSize(100, 100);
        leftArm2 = new AdvancedModelRenderer(this, "LeftArm2");
        leftArm2.mirror = false;
        leftArm2.addBox(0.0F, -7.0F, -3.0F, 1, 2, 4);
        leftArm2.setTextureSize(100, 100);
        leftArm1.addChild(leftArm2);
        leftArmClaws = new AdvancedModelRenderer(this, "LeftArmClaws");
        leftArmClaws.mirror = false;
        leftArmClaws.addBox(-0.5F, -6.0F, 1.0F, 1, 3, 1);
        leftArmClaws.setTextureSize(100, 100);
        leftArm1.addChild(leftArmClaws);
        rightArm2 = new AdvancedModelRenderer(this, "RightArm2");
        rightArm2.mirror = false;
        rightArm2.addBox(-1.0F, -7.0F, -3.0F, 1, 2, 4);
        rightArm2.setTextureSize(100, 100);
        rightArm1.addChild(rightArm2);
        rightArmClaws = new AdvancedModelRenderer(this, "RightArmClaws");
        rightArmClaws.mirror = false;
        rightArmClaws.addBox(-0.5F, -6.0F, 1.0F, 1, 3, 1);
        rightArmClaws.setTextureSize(100, 100);
        rightArm1.addChild(rightArmClaws);
        leftLeg2 = new AdvancedModelRenderer(this, "LeftLeg2");
        leftLeg2.mirror = false;
        leftLeg2.addBox(0.0F, -12.0F, -3.5F, 2, 7, 2);
        leftLeg2.setTextureSize(100, 100);
        leftLeg1.addChild(leftLeg2);
        leftFoot = new AdvancedModelRenderer(this, "LeftFoot");
        leftFoot.mirror = false;
        leftFoot.addBox(0.0F, -13.0F, -3.5F, 2, 1, 4);
        leftFoot.setTextureSize(100, 100);
        leftLeg1.addChild(leftFoot);
        leftClaw = new AdvancedModelRenderer(this, "LeftClaw");
        leftClaw.mirror = false;
        leftClaw.addBox(0.0F, -12.0F, -1.5F, 0, 2, 2);
        leftClaw.setTextureSize(100, 100);
        leftLeg1.addChild(leftClaw);
        crest = new AdvancedModelRenderer(this, "Crest");
        crest.mirror = false;
        crest.addBox(-1.5F, 2.0F, 0.0F, 3, 1, 3);
        crest.setTextureSize(100, 100);
        head.addChild(crest);
        snoutTip = new AdvancedModelRenderer(this, "SnoutTip");
        snoutTip.mirror = false;
        snoutTip.addBox(-1.0F, -2.0F, 7.0F, 2, 3, 2);
        snoutTip.setTextureSize(100, 100);
        head.addChild(snoutTip);
        snout = new AdvancedModelRenderer(this, "Snout");
        snout.mirror = false;
        snout.addBox(-1.0F, -2.0F, 4.0F, 2, 4, 3);
        snout.setTextureSize(100, 100);
        head.addChild(snout);
        tail2 = new AdvancedModelRenderer(this, "Tail2");
        tail2.mirror = false;
        tail2.addBox(-2.0F, -3.0F, -5.0F, 4, 5, 5);
        tail2.setTextureSize(100, 100);
        tail1.addChild(tail2);
        rightLeg2 = new AdvancedModelRenderer(this, "RightLeg2");
        rightLeg2.mirror = false;
        rightLeg2.addBox(-2.0F, -12.0F, -3.5F, 2, 7, 2);
        rightLeg2.setTextureSize(100, 100);
        rightLeg1.addChild(rightLeg2);
        rightFoot = new AdvancedModelRenderer(this, "RightFoot");
        rightFoot.mirror = false;
        rightFoot.addBox(-2.0F, -13.0F, -3.5F, 2, 1, 4);
        rightFoot.setTextureSize(100, 100);
        rightLeg1.addChild(rightFoot);
        rightClaw = new AdvancedModelRenderer(this, "RightClaw");
        rightClaw.mirror = false;
        rightClaw.addBox(0.0F, -12.0F, -1.5F, 0, 2, 2);
        rightClaw.setTextureSize(100, 100);
        rightLeg1.addChild(rightClaw);
        tail3 = new AdvancedModelRenderer(this, "Tail3");
        tail3.mirror = false;
        tail3.addBox(-1.0F, -2.0F, -9.0F, 2, 4, 9);
        tail3.setTextureSize(100, 100);
        tail2.addChild(tail3);
        tail4 = new AdvancedModelRenderer(this, "Tail4");
        tail4.mirror = false;
        tail4.addBox(-1.0F, -2.0F, -9.0F, 2, 3, 9);
        tail4.setTextureSize(100, 100);
        tail3.addChild(tail4);
        tail5 = new AdvancedModelRenderer(this, "Tail5");
        tail5.mirror = false;
        tail5.addBox(-1.0F, -1.0F, -9.0F, 2, 2, 9);
        tail5.setTextureSize(100, 100);
        tail4.addChild(tail5);
        tail4Fan = new AdvancedModelRenderer(this, "Tail4Fan");
        tail4Fan.mirror = false;
        tail4Fan.addBox(-3.0F, -1.0F, -9.0F, 6, 1, 9);
        tail4Fan.setTextureSize(100, 100);
        tail4.addChild(tail4Fan);
        tail5Fan = new AdvancedModelRenderer(this, "Tail5Fan");
        tail5Fan.mirror = false;
        tail5Fan.addBox(-3.5F, -0.5F, -17.0F, 7, 1, 17);
        tail5Fan.setTextureSize(100, 100);
        tail5.addChild(tail5Fan);
    }

    @Override
    public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7) {
        leftArm1.render(par7);
        rightArm1.render(par7);
        neck1.render(par7);
        neck2.render(par7);
        body.render(par7);
        leftLeg1.render(par7);
        head.render(par7);
        tail1.render(par7);
        rightLeg1.render(par7);
    }
}
